apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: kubeapp
        image: your-dockerhub-username/kubeapp:latest
        ports:
        - containerPort: 3000
