apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 963665911471.dkr.ecr.us-east-1.amazonaws.com/poc-project:latest
        ports:
        - containerPort: 80