name: Build and Deploy to ECR

on:
  push:
    branches: [ main ]
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/poc-project:$IMAGE_TAG .
          docker push $ECR_REGISTRY/poc-project:$IMAGE_TAG

      - name: Update image tag in Kustomize overlay
        run: |
          sed -i "s|newTag:.*|newTag: ${{ github.sha }}|" kustomize/overlays/dev/kustomization.yaml
          git config user.name github-actions
          git config user.email actions@github.com
          git commit -am "Update image tag to ${{ github.sha }}"
          git push
